language: cpp

before_install:
  sudo apt-get install libcppdb-dev build-essential libboost-program-options-dev libgcrypt20-dev

compiler:
  - gcc

script: ./travis_build.script

notifications:
  email: false
